[build]
buildCommand = "npm ci && npm run build"
dockerBuildTarget = "runner"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/v1/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
