[build]
buildCommand = "npm ci && npm run build"
dockerBuildTarget = "runner"

[deploy]
startCommand = "node_modules/.bin/prisma migrate deploy && node dist/server.js"
healthcheckPath = "/v1/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
