import Foundation

/// #59: Curated history question bank. Each level ships ≥50 questions.
/// LK20-aligned: 1.–10. klasse → grunnskole, 11.–13. → VGS,
/// 14.–20. → universitet/avansert. Topics span Norge + verden, fra
/// forhistorie til moderne tid.
enum HistoryQuestionBank {

    typealias Raw = QuizProblemGenerator.Raw

    static func questions(forLevel level: Int) -> [Raw] {
        switch max(1, min(20, level)) {
        case 1:  return level1
        case 2:  return level2
        case 3:  return level3
        case 4:  return level4
        case 5:  return level5
        case 6:  return level6
        case 7:  return level7
        case 8:  return level8
        case 9:  return level9
        case 10: return level10
        case 11: return level11
        case 12: return level12
        case 13: return level13
        case 14: return level14
        case 15: return level15
        case 16: return level16
        case 17: return level17
        case 18: return level18
        case 19: return level19
        default: return level20
        }
    }

    private static func q(_ p: String, _ c: String, _ d1: String, _ d2: String, _ d3: String) -> Raw {
        Raw(prompt: p, correct: c, distractors: [d1, d2, d3])
    }

    // Level 1: Norge enkel + dagligliv før
    private static let level1: [Raw] = [
        q("Hva er Norges hovedstad?", "Oslo", "Bergen", "Trondheim", "Stavanger"),
        q("Når feirer vi Norges nasjonaldag?", "17. mai", "1. mai", "8. mai", "1. juni"),
        q("Hvilken konge har Norge i 2025?", "Harald V", "Olav V", "Haakon VII", "Carl XVI"),
        q("Hva heter Norges nasjonalsang?", "Ja, vi elsker dette landet", "Gud signe vårt dyre fedreland", "Mellom bakkar og berg", "Fagert er landet"),
        q("Hvilke farger har det norske flagget?", "Rød, hvit, blå", "Rød, hvit, gul", "Blå, hvit, grønn", "Gul, blå, hvit"),
        q("Hva ble Norge skilt fra i 1905?", "Sverige", "Danmark", "Finland", "Russland"),
        q("Hva het Norges første konge etter 1905?", "Haakon VII", "Olav V", "Harald V", "Magnus VI"),
        q("Hvilken by var Norges hovedstad i middelalderen (en periode)?", "Bergen", "Oslo", "Trondheim", "Tromsø"),
        q("Hvilken by ble grunnlagt av Olav Tryggvason?", "Trondheim (Nidaros)", "Oslo", "Bergen", "Stavanger"),
        q("Hva het hovedstaden Oslo en periode (1624–1925)?", "Christiania/Kristiania", "Akershus", "Bjørgvin", "Nidaros"),
        q("Hvilken konge ga Oslo navnet Christiania?", "Christian IV", "Christian VII", "Frederik III", "Hans"),
        q("Hva slags hus bodde mange i på bygdene før i tiden?", "Tømmerhus", "Glassbygg", "Skyskrapere", "Telt"),
        q("Hva slags transport brukte man før biler?", "Hest og vogn", "Buss", "Tog kun", "Fly"),
        q("Hva slags lys brukte man før strøm?", "Stearinlys/parafinlampe", "LED", "Lysstoffrør", "Halogen"),
        q("Hva slags varme brukte mange før sentralvarme?", "Vedovn", "Olje­fyrte panel direkte", "Solcelle­panel", "Varmepumpe"),
        q("Hva slags klær brukte vikinger?", "Ull og lin", "Polyester", "Silke kun", "Plast"),
        q("Hvor kom vikingene fra?", "Skandinavia", "Asia", "Afrika", "Sør-Amerika"),
        q("Hvilke skip brukte vikingene?", "Langskip", "Galei", "Trireme", "Galeon"),
        q("Hvilken havn er kjent for vikingfunn (Oseberg)?", "Oseberg", "Akershus", "Bryggen", "Lofoten"),
        q("Hvilket vikingfunn kalles 'Osebergskipet'?", "Et vikingskip", "Et hus", "En sverd", "En krone"),
        q("Hvor lå Norges erkebispesete i middelalderen?", "Nidaros (Trondheim)", "Bergen", "Oslo", "Stavanger"),
        q("Hva heter den store kirken i Trondheim?", "Nidarosdomen", "Oslo Domkirke", "Bryggen", "Akershus festning"),
        q("Hva slags festning ligger i Oslo?", "Akershus festning", "Bergenhus", "Vardøhus", "Fredriksten"),
        q("Hva slags festning ligger i Bergen?", "Bergenhus", "Akershus", "Vardøhus", "Fredriksten"),
        q("Hvilken bydel i Bergen er kjent for hansatiden?", "Bryggen", "Sandviken", "Møhlenpris", "Nordnes"),
        q("Hvilket forbund handlet på Bryggen i Bergen?", "Hansaforbundet", "EU", "FN", "NATO"),
        q("Hva er en konge?", "En statsoverhode i monarki", "En folkevalgt president", "En soldat", "En type bonde"),
        q("Hva er en dronning?", "Kvinnelig statsoverhode i monarki", "En type kake", "En type sko", "En type sang"),
        q("Hvor mange konger heter Haakon i Norge totalt?", "Flere (Haakon I–VII)", "1", "2", "3"),
        q("Hva het den første samlende kongen i Norge?", "Harald Hårfagre", "Olav den hellige", "Magnus Lagabøte", "Haakon V"),
        q("Hvor er slaget ved Hafrsfjord?", "Stavanger", "Oslo", "Bergen", "Trondheim"),
        q("Hvilken konge gjorde Norge kristent (sentralt)?", "Olav den hellige", "Harald Hårfagre", "Magnus Lagabøte", "Sverre"),
        q("Hvilken slag ble Olav den hellige drept i?", "Slaget ved Stiklestad", "Hafrsfjord", "Svolder", "Kalmar"),
        q("Hvilket år regnes for Olav den helliges død?", "1030", "1066", "872", "1814"),
        q("Hvilket land hadde Norge union med før Sverige?", "Danmark", "Tyskland", "Finland", "Island"),
        q("Hvor lenge varte Norges union med Danmark (omtrent)?", "Ca. 400 år", "Ca. 50 år", "Ca. 100 år", "Ca. 800 år"),
        q("Hvilket dokument ble skrevet i Eidsvoll 1814?", "Grunnloven", "Magna Carta", "FN-pakten", "Sverige-paktet"),
        q("Hvilken dato ble Norges grunnlov undertegnet?", "17. mai 1814", "1. mai 1814", "9. april 1814", "7. juni 1814"),
        q("Hvor møttes Eidsvollsmennene?", "Eidsvollsbygningen", "Akershus", "Stortinget", "Trondheim"),
        q("Hva kalles Norges nasjonalforsamling?", "Stortinget", "Folketinget", "Riksdagen", "Kongressen"),
        q("Hvor ligger Stortinget?", "Oslo", "Bergen", "Trondheim", "Stavanger"),
        q("Hvilket dyr finnes på Norges riksvåpen?", "Løve", "Ørn", "Bjørn", "Ulv"),
        q("Hva holder løven på riksvåpenet?", "En øks", "Et sverd", "En krone", "En bok"),
        q("Hvilket språk snakker man i Norge?", "Norsk", "Svensk", "Dansk", "Finsk"),
        q("Hvor mange offisielle skrift­former har norsk?", "2 (bokmål og nynorsk)", "1", "3", "4"),
        q("Hvem skapte landsmål (nynorsk)?", "Ivar Aasen", "Henrik Wergeland", "Bjørnstjerne Bjørnson", "Henrik Ibsen"),
        q("Hvilken forfatter skrev 'Et dukkehjem'?", "Henrik Ibsen", "Henrik Wergeland", "Bjørnson", "Hamsun"),
        q("Hvem skrev 'Sult'?", "Knut Hamsun", "Ibsen", "Bjørnson", "Wergeland"),
        q("Hva var Norge mest kjent for i kald krigstid (NATO 1949)?", "Medlemskap i NATO", "Medlem av Warszawa-pakten", "Nøytralt", "Kommunistisk"),
        q("Hvilket år ble Norge medlem av NATO?", "1949", "1945", "1972", "1994"),
        q("Hva slags styreform har Norge?", "Konstitusjonelt monarki", "Republikk", "Diktatur", "Føderasjon")
    ]

    // Level 2: Vikingtid + Norden
    private static let level2: [Raw] = [
        q("Når regnes vikingtiden å starte (cirka)?", "793 (Lindisfarne)", "1066", "500", "1000"),
        q("Når regnes vikingtiden å slutte (cirka)?", "1066", "793", "1500", "1814"),
        q("Hvilket angrep regnes som starten på vikingtiden?", "Plyndringen av Lindisfarne", "Slaget ved Hastings", "Slaget ved Stamford", "Slaget ved Hafrsfjord"),
        q("Hvilken konge falt i slaget ved Stamford Bridge 1066?", "Harald Hardråde", "Olav Tryggvason", "Sverre", "Magnus den gode"),
        q("Hvem oppdaget Grønland (saga)?", "Eirik Raude", "Leiv Eiriksson", "Ingolv Arnarson", "Harald Hardråde"),
        q("Hvem regnes som første nordboer i Vinland (Nord-Amerika)?", "Leiv Eiriksson", "Eirik Raude", "Olav Tryggvason", "Sverre"),
        q("Hvilket land koloniserte vikingene fra Norge mest (Nord-Atlanteren)?", "Island", "Spania", "Hellas", "Egypt"),
        q("Hvilket år ble Island bosatt (cirka)?", "874", "1000", "793", "1066"),
        q("Hvilken religion hadde vikingene?", "Norrøn (åsatru)", "Kristendom kun", "Islam", "Buddhisme"),
        q("Hvem var Tor i norrøn mytologi?", "Tordenguden", "Krigsguden eksklusivt", "Havets gud", "Underverdenens gud"),
        q("Hvem var Odin?", "Hovedguden i åsatru", "Havets gud", "Solens gud", "Måneguden"),
        q("Hvem var Loke?", "Trickster-figur", "Hovedgud", "Solgud", "Tordengud"),
        q("Hva het verdenstreet i norrøn mytologi?", "Yggdrasil", "Mjølner", "Valhall", "Bifrost"),
        q("Hva heter Tors hammer?", "Mjølner", "Gungner", "Skofnung", "Gram"),
        q("Hva heter regnbuebroen?", "Bifrost", "Yggdrasil", "Valhall", "Vanaheim"),
        q("Hvor kom døde krigere til ifølge norrøn tro?", "Valhall", "Helheim alltid", "Asgard nøkternt", "Vanaheim"),
        q("Hvilket språk skrev vikingene med?", "Runer (norrønt)", "Latinsk alfabet kun", "Kyrillisk", "Gresk"),
        q("Hva kalles vikingenes alfabet?", "Futhark", "Latin", "Kyrillisk", "Hebraisk"),
        q("Hva heter den eldste norrøne sagaen?", "Heimskringla (verk)", "Beowulf", "Iliaden", "Odysséen"),
        q("Hvem skrev Heimskringla?", "Snorre Sturlasson", "Ibsen", "Holberg", "Wergeland"),
        q("Hvilket land kom Snorre fra?", "Island", "Norge", "Danmark", "Sverige"),
        q("Hvor finnes Bryggen?", "Bergen", "Oslo", "Trondheim", "Tromsø"),
        q("Hvilken handelsby var hansa-base i Norge?", "Bergen", "Oslo", "Stavanger", "Tromsø"),
        q("Hvilket forbund dominerte Bergens handel?", "Hanseaten/Hansaforbundet", "EU", "Røde Kors", "FN"),
        q("Hvilket vareeksport var sentralt fra Bergen?", "Tørrfisk", "Olje", "Stål", "Korn"),
        q("Hvilket dyr brukte vikingene mest til transport på land?", "Hest", "Hund", "Esel", "Kamel"),
        q("Hvilket dyr fra havet var en stor proteinkilde?", "Sild", "Tunfisk", "Krabbe", "Hummer"),
        q("Hvor finner vi Osebergskipet i dag?", "Vikingskipshuset (planlagt nytt: Museum for vikingtiden, Oslo)", "Bergen Museum", "Akershus festning", "Nidarosdomen"),
        q("Hvilket vikingskip er funnet i Tønsberg-området (Gokstad)?", "Gokstadskipet", "Osebergskipet", "Tunaskipet", "Skuldelev-skipet"),
        q("Hvilken landsdel hadde sterk samisk kultur?", "Nord-Norge / Sápmi", "Sørlandet", "Vestlandet", "Østlandet"),
        q("Hva er Sápmi?", "Området hvor samene bor", "En by i Sør-Norge", "En sjø", "Et fjell"),
        q("Hva slags næring var/er sentral for samer (tradisjonelt)?", "Reindrift", "Hvalfangst", "Korndyrking alene", "Skipsbygging"),
        q("Hvilken sagn-figur er Magnus den gode?", "Norsk konge (1035–1047)", "Vikinghøvding", "Forfatter", "Maler"),
        q("Hvilken konge var Sverre Sigurdsson kjent for?", "Borgerkrig­stid mot bagler", "Slaget ved Hastings", "Vikingtokt mot Lindisfarne", "Eidsvoll"),
        q("Hva het Sverres parti?", "Birkebeinerne", "Baglerne", "Bondetoget", "Pommen"),
        q("Hva het motpartiet til birkebeinerne?", "Baglerne", "Bondetoget", "Eidsvollsmennene", "Stortingsmenn"),
        q("Hvilken berømt fortelling om en kongebaby gjelder Birkebeinerne?", "Håkon Håkonsson på ski", "Olav Tryggvason på elv", "Sverre på galei", "Harald Hårfagre i kornåker"),
        q("Hvor ligger Eidsvollsbygningen?", "Eidsvoll, Akershus/Innlandet", "Bergen", "Trondheim", "Stavanger"),
        q("Hvilken konge ble valgt på Eidsvoll i 1814?", "Christian Frederik", "Christian IV", "Karl Johan", "Haakon VII"),
        q("Hvor lenge var Norge i union med Sverige?", "1814–1905", "1380–1814", "1349–1500", "1905–1940"),
        q("Hvem var Norges konge i union med Sverige (først)?", "Karl Johan", "Christian Frederik", "Haakon VII", "Olav V"),
        q("Hva het svartedauden?", "Pestepidemien rundt 1349", "En krig", "En sky", "En sang"),
        q("Hvor stor andel av Norges befolkning antas svartedauden å ha drept?", "Cirka halvparten", "10 %", "100 %", "5 %"),
        q("Hvilket århundre var svartedauden i Norge?", "1300-tallet", "1500-tallet", "1700-tallet", "900-tallet"),
        q("Hva er Kalmarunionen?", "Norge, Sverige, Danmark fra 1397", "Bare Norge–Danmark", "Bare Sverige–Finland", "Russland–Finland"),
        q("Hva startet Kalmarunionen?", "1397", "1349", "1814", "1066"),
        q("Hva heter den danske dronningen som startet Kalmarunionen?", "Margrete I", "Margrete II", "Christine", "Sofie"),
        q("Hva het tospråklig fagbok-forfatter (1700-tallet)?", "Ludvig Holberg", "Ibsen", "Wergeland", "Bjørnson"),
        q("Hvilken konge bygde Christianiafestning?", "Christian IV", "Olav V", "Haakon VII", "Frederik VII"),
        q("Hvor flyttet Christian IV Oslo fra?", "Fra Gamlebyen til ved Akershus", "Til Bergen", "Til Trondheim", "Til Stavanger"),
        q("Hva heter den danskenorske felleskongelige familien?", "Oldenborg-/Glücksborg-ætten", "Bourbon", "Habsburg", "Romanov")
    ]

    // Level 3: Verden – oldtid (Egypt/Hellas/Roma)
    private static let level3: [Raw] = [
        q("Hvilken elv var sentral for det gamle Egypt?", "Nilen", "Tigris", "Eufrat", "Donau"),
        q("Hva het de største gravmonumentene i Egypt?", "Pyramidene", "Akropolis", "Stonehenge", "Forbidden City"),
        q("Hvor ligger pyramidene i Giza?", "Egypt", "Sudan", "Saudi-Arabia", "Israel"),
        q("Hva het en konge i det gamle Egypt?", "Farao", "Cæsar", "Sjah", "Tsar"),
        q("Hvilken kjent farao har en gylden maske?", "Tutankhamon", "Ramses III", "Kheops", "Khefren"),
        q("Hva het skriftspråket i det gamle Egypt?", "Hieroglyfer", "Latin", "Gresk", "Kyrillisk"),
        q("Hva er en mumie?", "En balsamert avdød kropp", "En gud", "En sykdom", "En type tre"),
        q("Hva heter byen knyttet til oldtidens Hellas?", "Athen", "Roma", "Kairo", "Babylon"),
        q("Hvilken bygning ligger på Akropolis?", "Parthenon", "Colosseum", "Hagia Sophia", "Pantheon"),
        q("Hvilket land startet de olympiske leker?", "Hellas", "Roma", "Egypt", "Persia"),
        q("Hvor ble de antikke OL holdt?", "Olympia", "Athen", "Sparta", "Delfi"),
        q("Hva het den greske visdomgudinnen?", "Athene", "Hera", "Afrodite", "Demeter"),
        q("Hva het hovedguden i den greske mytologien?", "Zevs", "Apollon", "Hades", "Ares"),
        q("Hvem var Sokrates?", "Filosof i Athen", "Romersk keiser", "Konge i Egypt", "Persisk hærfører"),
        q("Hvem var Sokrates' elev (kjent filosof)?", "Platon", "Aristoteles direkte", "Demokrit", "Heraklit"),
        q("Hvem var Platons elev?", "Aristoteles", "Sokrates", "Pythagoras", "Demokrit"),
        q("Hvem var lærer for Aleksander den store?", "Aristoteles", "Sokrates", "Platon", "Pythagoras"),
        q("Hvor ble Aleksander den stores rike basert?", "Makedonia", "Sparta", "Egypt", "Roma"),
        q("Hvor langt øst kom Aleksanders erobringer (cirka)?", "Til India", "Til Kina", "Til Japan", "Bare til Persia"),
        q("Hvilken antikk by ble grunnlagt 753 f.Kr. (mytisk)?", "Roma", "Athen", "Kairo", "Babylon"),
        q("Hvem var Roms grunnleggere ifølge sagn?", "Romulus og Remus", "Cæsar og Brutus", "Pontius og Pilatus", "Augustus og Tiberius"),
        q("Hva ble Roma kjent som etter republikken?", "Romerriket", "Bysants", "Det hellige romerske rike", "Egypt"),
        q("Hvilken keiser krysset Rubicon?", "Julius Cæsar", "Augustus", "Nero", "Trajan"),
        q("Hvilket år ble Cæsar drept?", "44 f.Kr.", "44 e.Kr.", "100 f.Kr.", "27 f.Kr."),
        q("Hva het den første romerske keiseren?", "Augustus", "Cæsar", "Nero", "Trajan"),
        q("Hva er Pompeii kjent for?", "Begravd av Vesuvs utbrudd", "Slaget ved Hastings", "OL", "Egyptisk grav"),
        q("Hvilket fjell la Pompeii i ruiner?", "Vesuv", "Etna", "Olympos", "Ararat"),
        q("Hva slags bygning er Colosseum?", "Romersk amfiteater", "Tempel", "Bibliotek", "Palass"),
        q("Hvilket språk ble brukt i Romerriket?", "Latin", "Gresk kun", "Egyptisk kun", "Kyrillisk"),
        q("Hvilken religion overtok i Romerriket fra 300-tallet?", "Kristendom", "Islam", "Buddhisme", "Norrøn"),
        q("Hvem regnes som kristendommens grunnlegger?", "Jesus", "Muhammed", "Buddha", "Sokrates"),
        q("Når oppsto kristendommen (cirka, e.Kr.)?", "1. århundre", "5. århundre", "7. århundre", "10. århundre"),
        q("Når falt Vest-Romerriket (cirka)?", "476", "1066", "800", "300"),
        q("Hva ble Øst-Romerriket kalt?", "Bysants", "Vest-Romerriket", "Karolinske rike", "Mongolriket"),
        q("Hva heter Bysants' hovedstad?", "Konstantinopel", "Roma", "Athen", "Kairo"),
        q("Hva heter Konstantinopel i dag?", "Istanbul", "Athen", "Beograd", "Sofia"),
        q("Hvilken konge samlet det frankiske riket?", "Karl den store", "Vilhelm Erobreren", "Justinian", "Cæsar"),
        q("Hvilket år ble Karl den store kronet til keiser?", "800", "1066", "476", "1492"),
        q("Hvem var pave i Karl den stores kroningen?", "Leo III", "Gregor I", "Innocens III", "Bonifatius VIII"),
        q("Hvilken bok regnes som hellig i kristendommen?", "Bibelen", "Koranen", "Toraen", "Vedaene"),
        q("Hvilken bok regnes som hellig i islam?", "Koranen", "Bibelen", "Toraen", "Vedaene"),
        q("Hvilken bok regnes som hellig i jødedommen?", "Toraen", "Koranen", "Bibelen (NT)", "Vedaene"),
        q("Hvor oppsto islam?", "Den arabiske halvøy", "Egypt", "India", "Roma"),
        q("Hvem grunnla islam?", "Muhammed", "Buddha", "Jesus", "Konfutse"),
        q("Hvilket år regnes som islams begynnelse (Hijra)?", "622", "570", "1066", "476"),
        q("Hvor er islams hellige by?", "Mekka", "Roma", "Athen", "Kairo"),
        q("Hva er det greske ordet for 'by-stat'?", "Polis", "Demos", "Aristos", "Ethnos"),
        q("Hva er demokrati direkte oversatt?", "Folkestyre", "Kongestyre", "Adelens styre", "Generalens styre"),
        q("Hvor er demokratiet sagt å ha oppstått?", "Athen", "Roma", "Kairo", "Persepolis"),
        q("Hva het Spartas berømte krigerklasse?", "Hoplitter (eller spartiater)", "Romulus", "Filosofer", "Slaver bare")
    ]

    // Level 4: Middelalder + Renessanse intro
    private static let level4: [Raw] = [
        q("Hva regnes som middelalderens varighet (Europa)?", "Ca. 500–1500", "0–500", "1500–1900", "1700–1900"),
        q("Hva slags samfunn var middelalderen sentralt preget av?", "Føydalisme", "Industri­samfunn", "Digital-samfunn", "Fiske­samfunn alene"),
        q("Hva er en føydal vasall?", "Jordherre under en konge/lensherre", "En slave", "En soldat alene", "En prest"),
        q("Hva er korstog?", "Religiøse felttog (kristne mot Midtøsten m.m.)", "OL", "Romerriket", "Eidsvoll"),
        q("Når startet det første korstoget?", "1096", "476", "1492", "1066"),
        q("Hvem ledet det første korstoget?", "Adelsmenn fra Vest-Europa (pavens kall)", "Karl den store", "Cæsar", "Vilhelm Erobreren"),
        q("Hva er Magna Carta?", "Frihetsbrev fra 1215, England", "Romersk lov", "Bysantinsk dekret", "Norsk grunnlov"),
        q("Hvilken konge undertegnet Magna Carta?", "Johan uten land", "Vilhelm Erobreren", "Henrik VIII", "Edvard III"),
        q("Hvem invaderte England 1066?", "Vilhelm Erobreren (Normandie)", "Olav Tryggvason", "Karl den store", "Cæsar"),
        q("Hvor sto slaget i 1066?", "Hastings", "Stamford Bridge (også 1066)", "Bosworth", "Trafalgar"),
        q("Hvilken religion vokste raskt i middelalderen i Europa?", "Kristendom", "Islam", "Buddhisme", "Hinduisme"),
        q("Hvem ledet katolsk kirke?", "Paven", "Patriarken kun", "Erkebiskopen i Canterbury", "Calvinister"),
        q("Hva er en katedral?", "Stor biskoppelig kirke", "En type slott", "Et kloster", "Et bibliotek"),
        q("Hva slags kunst-stil var dominant tidlig i middelalderen?", "Romansk", "Gotisk", "Barokk", "Klassisk"),
        q("Hva slags kunst-stil dominerer høymiddelalderen?", "Gotisk", "Romansk", "Barokk", "Empire"),
        q("Hva slags element kjennetegner gotisk?", "Spisse buer", "Halvbuer", "Kupler kun", "Søyler doriske"),
        q("Hva er svartedauden?", "Pestepidemi rundt 1346–1353", "En krig", "En storm", "En vulkan"),
        q("Hvor mange europeere er antatt drept av svartedauden?", "Cirka 1/3", "1 %", "100 %", "5 %"),
        q("Hvilket språk dominerte i middelalderens Europa (lærdt)?", "Latin", "Engelsk", "Norsk", "Fransk eksklusivt"),
        q("Hvem skrev 'Den guddommelige komedie'?", "Dante Alighieri", "Shakespeare", "Voltaire", "Rousseau"),
        q("Hvor ble Dante født?", "Firenze", "Roma", "Paris", "London"),
        q("Når levde Dante (cirka)?", "1265–1321", "1500-tallet", "1700-tallet", "900-tallet"),
        q("Hvem oppfant boktrykkerkunst i Europa?", "Gutenberg", "Da Vinci", "Galileo", "Newton"),
        q("Når oppfant Gutenberg trykkpressen (cirka)?", "Ca. 1450", "Ca. 1066", "Ca. 1700", "Ca. 1900"),
        q("Hvilken bok ble Gutenberg kjent for å trykke?", "Bibelen", "Koranen", "Iliaden", "Beowulf"),
        q("Hvor startet renessansen?", "Italia (Firenze)", "Frankrike", "Tyskland", "England"),
        q("Når startet renessansen (cirka)?", "1300–1400-tallet", "500-tallet", "1700-tallet", "1900-tallet"),
        q("Hvem malte 'Mona Lisa'?", "Leonardo da Vinci", "Michelangelo", "Raphael", "Caravaggio"),
        q("Hvem malte taket i Det sixtinske kapell?", "Michelangelo", "Da Vinci", "Raphael", "Donatello"),
        q("Hvilken kunstner laget 'David'-statuen?", "Michelangelo", "Donatello", "Bernini", "Da Vinci"),
        q("Hvilket land lå Reformasjonen sentralt i?", "Tyskland", "Italia", "England eksklusivt", "Spania"),
        q("Hvem startet Reformasjonen?", "Martin Luther", "Calvin alene", "Henrik VIII", "Knox"),
        q("Hvilket år hang Luther opp sine 95 teser (tradisjonelt)?", "1517", "1066", "1453", "1492"),
        q("Hvilken kirke ble dannet i kjølvannet av reformasjonen?", "Protestantisk (luthersk osv.)", "Katolsk", "Ortodoks", "Mormon"),
        q("Hva ble England under Henrik VIII religiøst?", "Anglikansk", "Katolsk fortsatt", "Ortodoks", "Lutheransk"),
        q("Hvem oppdaget Amerika for Europa (1492)?", "Columbus", "Vasco da Gama", "Marco Polo", "Magellan"),
        q("Hvilket land sponset Columbus' reise?", "Spania", "Portugal", "England", "Frankrike"),
        q("Hvem først seilte rundt Afrika til India?", "Vasco da Gama", "Columbus", "Cortez", "Pizarro"),
        q("Hvem ledet første jord-omseiling?", "Magellan (avsluttet av Elcano)", "Columbus", "Da Gama", "Drake"),
        q("Hvilket aztekriket ble erobret av Cortez?", "Mexico (Aztekene)", "Inka", "Maya alene", "Egypt"),
        q("Hvilket inkarike ble erobret av Pizarro?", "Inka (Peru)", "Aztek (Mexico)", "Maya alene", "Egypt"),
        q("Hva slags handelsvarer ga 'kolumbiansk utveksling'?", "Mat (potet, mais, tomat) m.m. mellom kontinenter", "Bare gull", "Bare slaver", "Bare epler"),
        q("Hvilken religion brakte erobrerne til Amerika?", "Kristendom (katolisisme)", "Islam", "Buddhisme", "Norrøn"),
        q("Hvem regnes som naturvitenskapens far (Galilei)?", "Galileo Galilei", "Newton kun", "Einstein", "Darwin"),
        q("Hva oppdaget Galileo med teleskop?", "Måner rundt Jupiter, kraterne på månen m.m.", "Atombomben", "Pencillin", "Røntgen"),
        q("Hvem laget den heliosentriske modellen?", "Kopernikus", "Ptolemaios", "Aristoteles", "Galilei først"),
        q("Hvem skrev 'Principia Mathematica'?", "Isaac Newton", "Galileo", "Einstein", "Da Vinci"),
        q("Hvilket århundre regnes som vitenskapelig revolusjon?", "1500–1700-tallet", "1900-tallet", "1100-tallet", "300-tallet"),
        q("Hva er trykkfrihetens første grunnstein i Norden?", "Trykkfrihet (1700–1800-tallet)", "Latin alene", "Bare i Italia", "Aldri i Norden"),
        q("Hva er en humanist (renessansen)?", "Lærd som verdsetter klassisk kultur", "En soldat", "En prest alene", "En bonde")
    ]

    // Level 5: Norge i union, dansk-norsk tid
    private static let level5: [Raw] = [
        q("Hvilken konge var i 1814 utropt i Eidsvoll?", "Christian Frederik", "Karl Johan", "Haakon VII", "Olav V"),
        q("Hvor lenge varte unionen mellom Norge og Sverige?", "1814–1905", "1380–1814", "1349–1500", "1066–1349"),
        q("Hvem var konge i Norge ved unions­oppløsningen 1905?", "Oscar II → Haakon VII", "Karl Johan", "Christian Frederik", "Frederik VI"),
        q("Hvem ble valgt til konge etter 1905?", "Haakon VII", "Olav V", "Harald V", "Carl XVI"),
        q("Hva het Haakon VIIs sønn (kronprins)?", "Olav (V)", "Harald (V)", "Carl", "Magnus"),
        q("Hvilken statsminister fikk Norge i 1814 (kort tid)?", "Frederik Stang ikke da; spørsmål: hvem ledet Eidsvolls­møtet — Christian Frederik som regent", "Carl Johan", "Holberg", "Wergeland"),
        q("Hva er sentralt 1837-loven om?", "Formannskapslovene (lokalt selvstyre)", "Grunnloven", "FN-pakten", "EU-medlemskap"),
        q("Hva het den danske kongen som signerte Kielfreden?", "Frederik VI", "Christian VIII", "Christian IV", "Frederik III"),
        q("Hvilket år ble Kielfreden inngått?", "1814", "1809", "1809–14 generelt", "1864"),
        q("Hva ble Norge avstått til i Kielfreden?", "Sverige", "Tyskland", "Russland", "England"),
        q("Hva slags eksport drev Norge mye av på 1800-tallet?", "Tre/trelast og fisk", "Olje", "Stål", "Bil"),
        q("Hva het Norges nasjonalromantiske komponist?", "Edvard Grieg", "Beethoven", "Mozart", "Wagner"),
        q("Hva het den kjente norske maleren av nasjonalromantikken (landskap)?", "J.C. Dahl", "Munch", "Tidemand", "Eckersberg"),
        q("Hvilken maler står bak 'Brudeferd i Hardanger'?", "Tidemand & Gude", "Munch", "Dahl", "Heyerdahl"),
        q("Hvilken maler står bak 'Skrik'?", "Edvard Munch", "Christian Krohg", "Tidemand", "Dahl"),
        q("Hvilket land emigrerte mange nordmenn til på 1800-tallet?", "USA", "Australia kun", "India", "Japan"),
        q("Hvilken stat i USA fikk mange norske bosettere?", "Minnesota", "Florida", "Texas alene", "Hawaii"),
        q("Hvilken industri vokste fram i Norge sent 1800-tallet?", "Treforedling, gruvedrift", "Romfart", "Bilfabrikker", "Halvleder"),
        q("Hva ble bygget på Oseberg/Vigeland (Oslo)?", "Vigelandsparken", "Bygdøy alle museer på 1300-tallet", "Akershus tegning fra 1900", "Bryggen i Oslo"),
        q("Hvem var Henrik Wergeland?", "Norsk dikter, 1808–1845", "Maler", "Konge", "Statsminister"),
        q("Hva er Wergeland kjent for politisk?", "Kjempet for jødeparagrafens fjerning", "EU-medlemskap", "NATO", "FN"),
        q("Når ble jødeparagrafen fjernet?", "1851", "1814", "1905", "1945"),
        q("Hvem skrev 'Ja, vi elsker dette landet'?", "Bjørnstjerne Bjørnson", "Ibsen", "Hamsun", "Wergeland"),
        q("Hvem komponerte musikken til 'Ja, vi elsker'?", "Rikard Nordraak", "Grieg", "Sinding", "Sæverud"),
        q("Hvem skrev 'Synnøve Solbakken'?", "Bjørnson", "Ibsen", "Hamsun", "Vinje"),
        q("Hvem skrev 'Peer Gynt'?", "Ibsen", "Bjørnson", "Hamsun", "Wergeland"),
        q("Hvem komponerte musikken til 'Peer Gynt'?", "Edvard Grieg", "Sinding", "Wagner", "Beethoven"),
        q("Hva het Norges første statsminister i Stockholm (etter 1814)?", "Peder Anker", "Stang", "Sverdrup", "Michelsen"),
        q("Hvem var statsminister da unionen ble oppløst 1905?", "Christian Michelsen", "Stang", "Sverdrup", "Mowinckel"),
        q("Hvilken folkeavstemning ble holdt høsten 1905?", "Om monarki/republikk + om Karl/ Haakon", "Om EU", "Om kvinnelig stemmerett", "Om alkohol"),
        q("Hvilket år fikk kvinner stemmerett i Norge (alle)?", "1913", "1905", "1924", "1945"),
        q("Hvilken kvinne var pioner i kvinnesak (Camilla Collett)?", "Camilla Collett", "Aasta Hansteen", "Fernanda Nissen", "Kitty L. Kielland"),
        q("Hvilken oppdager nådde Sydpolen 1911?", "Roald Amundsen", "Robert Scott (kom etter)", "Nansen", "Sverdrup"),
        q("Hvem laget 'Fram'-skipet kjent?", "Fridtjof Nansen", "Sverdrup", "Heyerdahl", "Amundsen"),
        q("Hvem fikk Nobels fredspris 1922?", "Fridtjof Nansen", "Bjørnson", "Hamsun", "Trygve Lie"),
        q("Hvem var FNs første generalsekretær?", "Trygve Lie (Norge)", "Hammarskjöld", "U Thant", "Annan"),
        q("Hvilket land var i union med Norge 1380–1814?", "Danmark", "Sverige", "Russland", "Finland"),
        q("Hvilken konge gjorde Norge til lutheransk (1537)?", "Christian III", "Christian IV", "Frederik II", "Christian II"),
        q("Hvilket år regnes Norge som luthersk?", "1537", "1814", "1349", "1905"),
        q("Hva slags skikk er bunad?", "Tradisjonell folkedrakt", "Et instrument", "En matrett", "En hilsen"),
        q("Hvilket år ble bondetoget gjennomført (1814 før Eidsvoll)?", "Bondetoget gikk i 1818, men 'Riksforsamlingen' var 1814", "1066", "1349", "1900"),
        q("Hva slags bevegelse var venstresiden tidlig (1880-tallet)?", "Venstre, parlamentarisme", "Høyre, bevaringsorientert", "Senterpartiet", "Frp"),
        q("Hvem ble Norges første statsminister fra Venstre (parlamentarisme 1884)?", "Johan Sverdrup", "Michelsen", "Knudsen", "Mowinckel"),
        q("Hvilket år ble parlamentarisme innført?", "1884", "1814", "1905", "1945"),
        q("Hva het ledende avis i Christiania på 1800-tallet?", "Morgenbladet", "Aftenposten", "VG", "Dagbladet"),
        q("Når ble Aftenposten grunnlagt?", "1860", "1900", "1814", "1945"),
        q("Hvilken folkebevegelse vokste fram med haugianerne?", "Lavkirkelig, lekmannsbevegelse", "Industri­arbeider­bevegelse", "Avholds­bevegelse alene", "Idrett"),
        q("Hvem var Hans Nielsen Hauge?", "Lekpredikant tidlig 1800-tallet", "Konge", "Filosof", "Maler"),
        q("Hvilket nasjonsbygg-prosjekt var landsdekkende på 1800-tallet?", "Jernbane og post", "Romstasjon", "Atomkraftverk", "Olje­plattform"),
        q("Hvor gikk Norges første jernbane (1854)?", "Eidsvoll–Oslo (Christiania)", "Oslo–Bergen", "Oslo–Trondheim", "Oslo–Stavanger")
    ]

    // Level 6: 1900-tallet (Norge/verden)
    private static let level6: [Raw] = [
        q("Hvilket år startet 1. verdenskrig?", "1914", "1939", "1905", "1918"),
        q("Hvilket år sluttet 1. verdenskrig?", "1918", "1914", "1945", "1939"),
        q("Hva utløste 1. verdenskrig?", "Drapet på Franz Ferdinand", "Pearl Harbor", "Tysk angrep på Polen", "Berlin-mur"),
        q("Hvor ble Franz Ferdinand drept?", "Sarajevo", "Wien", "Berlin", "Beograd"),
        q("Var Norge i 1. verdenskrig?", "Nei (nøytralt)", "Ja, med Tyskland", "Ja, med Storbritannia", "Ja, med Russland"),
        q("Hvilken avtale avsluttet 1. verdenskrig?", "Versaillestraktaten", "Yalta", "Potsdam", "Wienerkongressen"),
        q("Hvilket organ ble dannet etter 1. verdenskrig?", "Folkeforbundet", "FN", "EU", "NATO"),
        q("Hvilket år startet 2. verdenskrig?", "1939", "1914", "1945", "1941"),
        q("Hvilket land ble invadert av Tyskland 1.9.1939?", "Polen", "Norge", "Frankrike", "Belgia"),
        q("Hvilket år ble Norge angrepet av Tyskland?", "1940", "1939", "1945", "1941"),
        q("Hvilken dato angrep Tyskland Norge?", "9. april 1940", "1. september 1939", "8. mai 1945", "17. mai 1940"),
        q("Hvor seilte Norges konge ut etter angrepet?", "Til London (eksil)", "Til Stockholm", "Til København", "Til Oslo"),
        q("Hva het den norske kvislingen?", "Vidkun Quisling", "Knut Hamsun", "Jonas Lie (politikeren)", "Terboven"),
        q("Hva het Tysklands rikskommissær i Norge?", "Josef Terboven", "Heinrich Himmler", "Reinhard Heydrich", "Albert Speer"),
        q("Hvor lenge var Norge okkupert?", "1940–1945", "1939–1945", "1942–1944", "1940–1942"),
        q("Hva het den norske motstandsbevegelsen?", "Hjemmefronten / Milorg", "Hitlerjugend", "Maquis", "Lehi"),
        q("Hva er kjent som tungtvanns­aksjonen?", "Sabotasjeaksjon i Rjukan", "OL i Lillehammer", "1814-grunnloven", "Atombomben i Hiroshima"),
        q("Hvor ligger Vemork (tungtvann)?", "Rjukan", "Notodden", "Kongsberg", "Trondheim"),
        q("Hvilken vinter ble Stalingrad-slaget avgjort?", "1942–1943", "1939–1940", "1943–1944", "1944–1945"),
        q("Hvem vant slaget om Stalingrad?", "Sovjetunionen", "Tyskland", "USA", "Storbritannia"),
        q("Hvilken dato landet de allierte i Normandie?", "6. juni 1944 (D-dag)", "8. mai 1945", "1. september 1939", "9. april 1940"),
        q("Hvilket år ble 2. verdenskrig avsluttet i Europa?", "1945 (8. mai)", "1944", "1939", "1941"),
        q("Hvilket land slapp atombombene over Japan?", "USA", "Storbritannia", "Sovjetunionen", "Tyskland"),
        q("Hvilke byer ble bombet med atombombe?", "Hiroshima og Nagasaki", "Tokyo og Osaka", "Yokohama og Nagoya", "Sapporo og Kobe"),
        q("Hvilket år ble FN dannet?", "1945", "1919", "1949", "1989"),
        q("Hva er FN sin forløper?", "Folkeforbundet", "EU", "NATO", "Kominform"),
        q("Hvilket år ble NATO dannet?", "1949", "1945", "1955", "1989"),
        q("Var Norge med i NATO fra 1949?", "Ja", "Nei (kom 1955)", "Nei (kom 1989)", "Aldri"),
        q("Hva het den østlige militæralliansen?", "Warszawapakten", "NATO", "EU", "ASEAN"),
        q("Hvilket år ble Tyskland delt?", "1949 (BRD/DDR)", "1945", "1961", "1989"),
        q("Hva het muren mellom Øst- og Vest-Berlin?", "Berlinmuren", "Den kinesiske mur", "Maginot-linjen", "Hadrians mur"),
        q("Når ble Berlinmuren bygget?", "1961", "1945", "1949", "1989"),
        q("Når falt Berlinmuren?", "1989", "1991", "1961", "2001"),
        q("Hvilket år ble Sovjetunionen oppløst?", "1991", "1989", "1995", "1985"),
        q("Hvem var sovjetisk leder ved Berlinmurens fall?", "Mikhail Gorbatsjov", "Bresjnev", "Krustsjov", "Stalin"),
        q("Hvem var Sovjetunionens første leder?", "Lenin", "Stalin", "Trotskij", "Krustsjov"),
        q("Hvilket år ble Russland til Sovjetunionen?", "1922", "1917", "1945", "1991"),
        q("Hvilket år var den russiske revolusjonen?", "1917", "1905", "1922", "1939"),
        q("Hvem ledet bolsjevikene i 1917?", "Lenin", "Stalin", "Trotskij", "Marx"),
        q("Hvem skrev 'Det kommunistiske manifest'?", "Marx og Engels", "Lenin", "Stalin", "Mao"),
        q("Når kom Norge inn i oljealderen?", "Sent 1960-tallet (Ekofisk 1969)", "1905", "1945", "1990"),
        q("Hvilket felt regnes som starten på norsk olje?", "Ekofisk", "Statfjord", "Snøhvit", "Goliat"),
        q("Hvilket år ble Norge medlem av EFTA?", "1960", "1949", "1972", "1994"),
        q("Hvilken folkeavstemning sa nei til EU/EF i Norge?", "1972 og 1994", "Bare 1994", "Bare 1972", "Bare 1985"),
        q("Hvilket år ble Sverige medlem av EU?", "1995", "1972", "1989", "2004"),
        q("Hvem var FNs generalsekretær 1953–1961?", "Dag Hammarskjöld", "Trygve Lie", "U Thant", "Boutros-Ghali"),
        q("Hvilken kald-krig-krise var i 1962 (Cuba)?", "Cubakrisen", "Berlinblokkaden", "Suezkrisen", "Vietnamkrigen"),
        q("Hvem var USAs president under Cubakrisen?", "John F. Kennedy", "Eisenhower", "Nixon", "Carter"),
        q("Hvem var sovjetisk leder under Cubakrisen?", "Krustsjov", "Stalin", "Bresjnev", "Gorbatsjov"),
        q("Hvor lenge varte Vietnamkrigen (USA-fasen)?", "1965–1975 (offisielt)", "1939–1945", "1950–1953", "1990–1995")
    ]

    // Level 7: Idéhistorie + Norge mellomkrig/etterkrig
    private static let level7: [Raw] = [
        q("Hva var opplysningstiden?", "Idéstrøm 1700-tallet, fornuft og frihet", "Kunstnerisk renessanse", "Industri­ell oppgang", "Kald krig"),
        q("Hvem skrev 'Om samfunnskontrakten'?", "Rousseau", "Voltaire", "Kant", "Locke"),
        q("Hvem skrev 'On Liberty'?", "John Stuart Mill", "Locke", "Rousseau", "Kant"),
        q("Hvem skrev 'Den protestantiske etikken'?", "Max Weber", "Karl Marx", "Adam Smith", "Durkheim"),
        q("Hvem skrev 'Wealth of Nations'?", "Adam Smith", "Marx", "Keynes", "Hayek"),
        q("Hvilken filosof formulerte kategorisk imperativ?", "Immanuel Kant", "Hegel", "Schopenhauer", "Nietzsche"),
        q("Hvem mente 'Gud er død'?", "Nietzsche", "Sartre", "Heidegger", "Camus"),
        q("Hvem var sentral i eksistensialismen?", "Sartre/Camus/Beauvoir", "Hegel", "Plato", "Aristoteles"),
        q("Hvem skrev 'Det andre kjønn'?", "Simone de Beauvoir", "Virginia Woolf", "Hannah Arendt", "Susan Sontag"),
        q("Hvem skrev '1984'?", "George Orwell", "Aldous Huxley", "Hemingway", "Steinbeck"),
        q("Hvem skrev 'Brave New World'?", "Aldous Huxley", "Orwell", "Bradbury", "Asimov"),
        q("Hvilken bevegelse vokste fram i Norge etter 1945?", "Sosialdemokratisk velferdstat", "Fascisme", "Monarkisme stort", "Anarkisme"),
        q("Hvem var Norges statsminister 1945–1951?", "Einar Gerhardsen", "Trygve Bratteli", "Per Borten", "Bondevik"),
        q("Hvilket parti dominerte etterkrigs-Norge?", "Arbeiderpartiet", "Høyre", "SV", "Venstre"),
        q("Når fikk Norge folketrygdloven?", "1967", "1945", "1972", "1990"),
        q("Når ble likestillingsloven (Norge) vedtatt?", "1978", "1945", "1990", "2005"),
        q("Når ble likestillings­ombudet etablert?", "1979", "1990", "2000", "2018"),
        q("Hva er 'Marshallplanen'?", "USAs gjenoppbyggingsplan for Europa etter 2. vk.", "FN-plan", "Sovjet-plan", "EU-plan"),
        q("Hvilket år startet Marshallplanen?", "1948", "1945", "1955", "1961"),
        q("Hva er Bretton Woods?", "Avtalesystem for valutakurser/IMF/Verdensbanken (1944)", "Avtale om EU", "FN-pakt", "NATO-pakt"),
        q("Hvilket år ble menneskerettighets­erklæringen vedtatt av FN?", "1948", "1945", "1989", "1969"),
        q("Hvor ble menneske­rettighets­erklæringen vedtatt?", "I Paris", "I Roma", "I Genève", "I New York"),
        q("Hvem var sentral redaktør (Eleanor Roosevelt) i menneske­rettighets­erklæringen?", "Eleanor Roosevelt", "Margaret Thatcher", "Indira Gandhi", "Madeleine Albright"),
        q("Hvilket år ble Sør-Afrika kvitt apartheid?", "1994", "1989", "1980", "2000"),
        q("Hvem ble Sør-Afrikas første svarte president?", "Nelson Mandela", "Desmond Tutu", "Thabo Mbeki", "Mugabe"),
        q("Hvor lenge satt Mandela i fengsel?", "27 år", "10 år", "40 år", "5 år"),
        q("Hvem ledet ikke-volds­bevegelsen i India?", "Mahatma Gandhi", "Nehru", "Bose", "Modi"),
        q("Når ble India selvstendig?", "1947", "1857", "1900", "1971"),
        q("Hvem var første statsminister i India?", "Jawaharlal Nehru", "Indira Gandhi", "Rajiv Gandhi", "Modi"),
        q("Hvilket år ble Pakistan dannet?", "1947", "1857", "1971", "1900"),
        q("Hvilket år ble Bangladesh dannet?", "1971", "1947", "1965", "1990"),
        q("Hva er Suezkrisen?", "1956 – Egypt nasjonalisering, intervensjon", "1973 – krig", "1948 – Israel grunnlagt", "1967 – seksdagerskrigen"),
        q("Hvilket år ble staten Israel etablert?", "1948", "1917", "1967", "1973"),
        q("Hva er seksdagerskrigen (1967)?", "Israel mot araber-stater", "Cubakrisen", "Vietnamkrigen", "Koreakrigen"),
        q("Når foregikk Koreakrigen?", "1950–1953", "1939–1945", "1965–1975", "1990–1991"),
        q("Hva het de USA-ledede styrkene i Koreakrigen?", "FN-styrker", "NATO", "ANZUS", "ASEAN"),
        q("Hvilket år ble Kina under kommunistene?", "1949", "1911", "1937", "1945"),
        q("Hvem ledet Kinas kommunistparti i 1949?", "Mao Zedong", "Deng Xiaoping", "Sun Yat-sen", "Chiang Kai-shek"),
        q("Hva het Kulturrevolusjonen?", "Politisk kampanje i Kina 1966–1976", "EU-program", "FN-prosjekt", "NATO-prosjekt"),
        q("Hva er det store spranget i Kina?", "Mao-kampanje 1958–1962", "Romfartsprosjekt", "Bretton Woods", "Marshallplanen"),
        q("Hvem var Maos etterfølger som reformerte Kina?", "Deng Xiaoping", "Hu Jintao", "Jiang Zemin", "Xi Jinping"),
        q("Hvilket år ble Hong Kong tilbakeført til Kina?", "1997", "1989", "2010", "1949"),
        q("Hvilket år var massakren på Den himmelske freds plass?", "1989", "1976", "1997", "2001"),
        q("Hvilken NATO-utvidelse skjedde i 1999?", "Polen, Tsjekkia, Ungarn", "Bare Norge", "Bare Tyskland", "Bare Italia"),
        q("Hvilken NATO-utvidelse skjedde i 2004?", "Sju østeuropeiske land", "Bare Polen", "Bare Tyrkia", "Bare Hellas"),
        q("Hva er Holocaust?", "Folkemord på jødene under nazismen", "En naturkatastrofe", "Et borgerkrig­slag", "En traktat"),
        q("Hvor mange jøder antas drept i Holocaust?", "Cirka 6 millioner", "1 million", "20 millioner", "100 000"),
        q("Hva er Auschwitz?", "Tysk konsentrasjons-/utryddelsesleir i Polen", "En slott", "En dom", "En by i Tyskland"),
        q("Når ble Auschwitz frigjort?", "27. januar 1945", "9. april 1940", "8. mai 1945", "6. juni 1944"),
        q("Hva er Nürnbergprosessene?", "Rettsoppgjør mot nazi-ledere etter 1945", "Folkemord-konvensjon", "Atomvåpenavtale", "OL")
    ]

    // Level 8: Norden + Norden i Europa
    private static let level8: [Raw] = [
        q("Hvilket år ble Sveriges union med Norge oppløst?", "1905", "1814", "1380", "1814–1905 var unionen"),
        q("Hva het den svenske kongen som måtte gå med på union 1814?", "Karl Johan (Karl XIV Johan) gikk inn i 1818 — i 1814 var det Karl XIII", "Gustav III", "Gustav IV", "Oscar II"),
        q("Hva het den franske generalen som ble svensk kronprins (1810)?", "Bernadotte (Karl Johan)", "Napoleon", "Murat", "Ney"),
        q("Hvilket år ble Finland skilt fra Sverige?", "1809", "1814", "1917", "1939"),
        q("Hva het Finland som del av Russland?", "Storfyrstedømmet Finland", "Russisk Karelen", "Polen-Finland", "Tsar-Finland"),
        q("Når ble Finland selvstendig?", "1917", "1809", "1939", "1945"),
        q("Hva het krigen Finland mot Sovjet 1939–40?", "Vinterkrigen", "Fortsettelseskrigen", "Lapplandskrigen", "Kontinuerligkrigen"),
        q("Hvilken krig fulgte Vinterkrigen (1941–44)?", "Fortsettelseskrigen", "Lapplandskrigen", "Vinterkrigen 2", "Andre verdenskrig kun"),
        q("Hva slags styreform har Sverige?", "Konstitusjonelt monarki", "Republikk", "Diktatur", "Føderalt"),
        q("Hva slags styreform har Finland?", "Republikk", "Monarki", "Diktatur", "Føderalt"),
        q("Hva slags styreform har Danmark?", "Konstitusjonelt monarki", "Republikk", "Diktatur", "Føderasjon"),
        q("Hva slags styreform har Island?", "Republikk", "Monarki", "Diktatur", "Føderasjon"),
        q("Hva er Norden definert som?", "Norge, Sverige, Danmark, Finland, Island (+ Færøyene/Grønland/Åland)", "Bare Norden 5 land", "Bare Skandinavia 3", "EU-områder"),
        q("Hva slags samarbeid er Nordisk råd?", "Nordisk parlamentarisk samarbeid", "Bare militært", "Bare økonomisk-fond", "Bare sport"),
        q("Når ble Nordisk råd dannet?", "1952", "1945", "1972", "1995"),
        q("Hva er Schengen-området?", "Europeisk pass-fri sone", "EU-tollunion alene", "FN-organisasjon", "NATO"),
        q("Når ble Norge med i Schengen?", "2001", "1989", "1994", "2010"),
        q("Hvilket år ble EU dannet (Maastricht)?", "1993", "1957", "1995", "2002"),
        q("Hvilket år kom euroen som mynt-/seddel-valuta?", "2002", "1999", "1995", "2008"),
        q("Hvilke nordiske land bruker euro?", "Finland", "Bare Norge", "Bare Sverige", "Alle"),
        q("Hvilke nordiske land er EU-medlemmer?", "Sverige, Danmark, Finland", "Bare Sverige", "Bare Danmark", "Alle"),
        q("Hvilke nordiske land er NATO-medlemmer (per 2024)?", "Norge, Danmark, Island, Finland, Sverige", "Bare Norge", "Bare Danmark og Norge", "Bare Sverige og Norge"),
        q("Når ble Finland NATO-medlem?", "2023", "2017", "1949", "1995"),
        q("Når ble Sverige NATO-medlem?", "2024", "2023", "1949", "1995"),
        q("Hva het Sveriges kjente statsminister drept 1986?", "Olof Palme", "Tage Erlander", "Ingvar Carlsson", "Göran Persson"),
        q("Hvor ble Olof Palme drept?", "Stockholm", "Göteborg", "Malmö", "Uppsala"),
        q("Hvilken svensk konge tar trone i 1973?", "Carl XVI Gustaf", "Gustav VI Adolf", "Gustav V", "Carl XV"),
        q("Hvilken konge har Danmark fra 2024?", "Frederik X", "Margrete II (til 2024)", "Christian X", "Christian IX"),
        q("Hvilken dronning regjerte Danmark 1972–2024?", "Margrete II", "Margrete I", "Anne-Marie", "Sofie"),
        q("Hva slags språkfamilie hører finsk til?", "Finsk-ugrisk (uralisk)", "Indoeuropeisk", "Tyrkisk", "Slavisk"),
        q("Hva slags språkfamilie hører norsk til?", "Indoeuropeisk (germansk)", "Finsk-ugrisk", "Slavisk", "Tyrkisk"),
        q("Hvilket språk er nærmest norsk?", "Dansk og svensk", "Finsk", "Engelsk alene", "Tysk alene"),
        q("Hvilket språk er kjent som det nordiske moderspråket?", "Norrønt", "Latin", "Gotisk", "Sanskrit"),
        q("Hvilken nordisk forfatter fikk Nobelprisen 1903?", "Bjørnstjerne Bjørnson", "Hamsun (1920)", "Selma Lagerlöf (1909)", "Sigrid Undset (1928)"),
        q("Hvilken norsk forfatter fikk Nobelprisen 1928?", "Sigrid Undset", "Hamsun (1920)", "Bjørnson (1903)", "Jon Fosse (2023)"),
        q("Hvilken norsk forfatter fikk Nobelprisen 1920?", "Knut Hamsun", "Bjørnson", "Undset", "Fosse"),
        q("Hvilken norsk forfatter fikk Nobelprisen i 2023?", "Jon Fosse", "Karl Ove Knausgård", "Erlend Loe", "Aksel Sandemose"),
        q("Hvilken film­regissør er Roy Andersson?", "Svensk", "Norsk", "Dansk", "Finsk"),
        q("Hvilken filmregissør er Lars von Trier?", "Dansk", "Svensk", "Norsk", "Finsk"),
        q("Hvilken filmregissør er Aki Kaurismäki?", "Finsk", "Svensk", "Norsk", "Dansk"),
        q("Hvilken filmregissør er Joachim Trier?", "Norsk", "Dansk", "Svensk", "Finsk"),
        q("Hvilken regissør laget 'Ingrid Bergman'-filmer (klassisk)?", "Bergman var skuespiller; spørsmål om regissør Ingmar Bergman?", "Lars von Trier", "Aki Kaurismäki", "Roy Andersson"),
        q("Hvilken Nordsjø-stat er minst i areal?", "Danmark", "Norge", "Sverige", "Finland"),
        q("Hvilket nordisk land er størst i areal?", "Sverige (Sverige > Finland > Norge > Island > Danmark fastland)", "Norge", "Finland", "Danmark"),
        q("Hva het det første store oljefeltet på norsk sokkel?", "Ekofisk", "Statfjord", "Snorre", "Goliat"),
        q("Når ble Statfjord-feltet startet (cirka)?", "Slutten av 1970-tallet", "1990-tallet", "1960-tallet", "2000-tallet"),
        q("Hva het oljeselskapet Statoil før 1981 (offisielt)?", "Den norske stats oljeselskap a.s (Statoil 1972)", "Hydro", "Equinor", "Saga"),
        q("Hva heter Statoil i dag (etter 2018)?", "Equinor", "Hydro", "Aker", "DNO"),
        q("Hvilket nordisk land har lengst kystlinje?", "Norge", "Sverige", "Finland", "Island"),
        q("Hvilken konge ledet Sverige under Karl XIIs slag?", "Karl XII", "Karl XI", "Karl IX", "Karl X")
    ]

    // Level 9: Norge i 2. verdenskrig + etterkrig
    private static let level9: [Raw] = [
        q("Hvor mange nordmenn falt i 2. verdenskrig (cirka)?", "Cirka 10 000", "Cirka 1 000", "Cirka 100 000", "Cirka 1 million"),
        q("Hvor lenge varte slaget om Narvik?", "Til juni 1940", "Til mai 1940", "Til 1945", "Til 1942"),
        q("Hvilket land sendte ekspedisjon til Norge 1940?", "Storbritannia/Frankrike (allierte)", "USA", "Sovjet", "Japan"),
        q("Hvilken motstandsgruppe utførte tungtvann-aksjonen?", "Lark-/Gunnerside-Linge-kompani", "Hjemmestyrkene mest", "Sjøforsvaret alene", "Hæren"),
        q("Hva slags fartøy het 'D/S Hydro'?", "Ferje med tungtvann (sprengt)", "Et tankskip", "En jager", "En undervannsbåt"),
        q("Hvor ligger fangeleiren Grini?", "Bærum", "Oslo sentrum", "Trondheim", "Bergen"),
        q("Hvor ligger fangeleiren Falstad?", "Levanger/Trøndelag", "Bærum", "Oslo", "Bergen"),
        q("Hvor er minnesmerket etter Holocaust i Norge?", "Akershuskaia (HL-senteret nær Bygdøy)", "Bryggen", "Vikingmuseet", "Akershus festning"),
        q("Hvor mange jøder ble deportert fra Norge?", "Cirka 770 (mest til Auschwitz)", "Cirka 100", "Cirka 10 000", "Cirka 50"),
        q("Hva het skipet brukt til deportasjon i 1942?", "DS Donau", "MS Stavanger", "DS Skagen", "MS Norge"),
        q("Hva het ledende avis i hjemmefronten?", "Bulletinen / illegale aviser", "Aftenposten", "VG", "Dagbladet"),
        q("Hva er kjent som 'Vidkun-saken'?", "Quisling-rettssaken", "Hauge-saken", "Tungtvann-saken", "Eidsvoll-saken"),
        q("Hva ble Quisling dømt for?", "Landsforræderi", "Tyveri", "Snikbruk av strøm", "Diktning"),
        q("Når ble Quisling henrettet?", "24. oktober 1945", "8. mai 1945", "9. april 1946", "17. mai 1946"),
        q("Hvem ledet Norges regjering i London under krigen?", "Johan Nygaardsvold (Ap)", "Einar Gerhardsen", "Christian Michelsen", "Trygve Lie"),
        q("Hva het utenriksministeren i Londonregjeringen?", "Trygve Lie", "Halvdan Koht (først, til 1940)", "Bratteli", "Per Borten"),
        q("Hvor lå Norges regjering i eksil?", "London", "New York", "Stockholm", "Reykjavík"),
        q("Hvor ble Tirpitz senket?", "Tromsø-området (Håkøya)", "Narvik", "Bergen", "Oslo"),
        q("Når ble Tirpitz senket?", "12. november 1944", "9. april 1940", "8. mai 1945", "1942"),
        q("Hvilken landsdel var brent ned (Lapplandskrig)?", "Finnmark", "Vestlandet", "Sørlandet", "Trøndelag"),
        q("Når brant tyskerne ned Finnmark?", "1944–45", "1940", "1942", "1945–46"),
        q("Hvor mange ble fordrevet i Finnmark?", "Cirka 50 000", "Cirka 1000", "Cirka 1 million", "Cirka 100"),
        q("Hva het tysk Wehrmacht-sjef i Norge?", "Falkenhorst", "Terboven", "Quisling", "Rommel"),
        q("Hva het den tyske marinens styrke i Norge?", "Kriegsmarine-styrkene (Tirpitz, Scharnhorst etc.)", "Wehrmacht alene", "U-Boot-kongressen", "Luftwaffe-flåten"),
        q("Hva er kjent som 'Måløy-raidet'?", "Britisk kommandoraid 1941", "OL i Lillehammer", "1814-grunnloven", "Eidsvoll-møtet"),
        q("Hva het etterkrigs-pakke i utenrikspolitikk Norge?", "Atlanterhavspakten/NATO + 'broen-byggings' politikk", "EU-medlemskap", "Bare nøytralitet", "Bare nordisk forsvarsforbund"),
        q("Hvilket alternativ ble valgt 1948–49: NATO eller nordisk forsvarsforbund?", "NATO", "Nordisk forsvarsforbund", "Egen rute", "Sovjet-allians"),
        q("Hvem var statsminister 1955–63?", "Einar Gerhardsen (forsvarte landet politisk lenge)", "Bratteli", "Borten", "Korvald"),
        q("Hvilken sak felte Gerhardsen i 1963?", "Kings Bay-ulykken", "Lofotsaken", "EU-saken", "Tungtvann-saken"),
        q("Hva er Kings Bay-saken?", "Gruveulykke på Svalbard 1962, kabinettsspørsmål", "Et rovdyrforlik", "En klimasak", "En oljekonflikt"),
        q("Hvem ble statsminister etter Gerhardsen i 1965?", "Per Borten (Sp)", "Bratteli (Ap)", "Korvald (Krf)", "Brundtland"),
        q("Hvem var Norges første kvinnelige statsminister?", "Gro Harlem Brundtland", "Kristin Halvorsen", "Erna Solberg", "Karita Bekkemellem"),
        q("Hvilket år ble Brundtland statsminister først?", "1981", "1990", "1986", "1996"),
        q("Hva er kjent som 'kvinneregjeringen'?", "Brundtlands regjering 1986 (40 % kvinner)", "Stoltenbergs 2005-regjering", "Solbergs", "Nygaardsvolds"),
        q("Hvem etterfulgte Brundtland som AP-leder?", "Thorbjørn Jagland", "Stoltenberg direkte", "Bratteli", "Bondevik"),
        q("Hvem var statsminister 2000–01?", "Jens Stoltenberg (først)", "Kjell Magne Bondevik", "Jagland", "Brundtland"),
        q("Hvem ble statsminister etter Stoltenberg 2001?", "Bondevik (II)", "Jagland", "Brundtland", "Solberg"),
        q("Hvem ble statsminister 2005–13?", "Jens Stoltenberg (rødgrønn)", "Bondevik", "Erna Solberg", "Jagland"),
        q("Hvem var statsminister 2013–21?", "Erna Solberg (Høyre)", "Stoltenberg", "Bondevik", "Støre"),
        q("Hvem ble statsminister i 2021?", "Jonas Gahr Støre", "Solberg", "Vedum", "Bondevik"),
        q("Hvilken FN-rolle har Stoltenberg etter 2014?", "NATO-generalsekretær (2014–2024)", "FN-generalsekretær", "EU-president", "Verdensbank-sjef"),
        q("Hvilket år tok terror på Utøya og Oslo sted?", "22. juli 2011", "11. september 2001", "1. mai 2010", "17. mai 2012"),
        q("Hvor mange ble drept i 22. juli-angrepene?", "77", "20", "200", "10"),
        q("Hva het gjerningsmannen?", "Anders Behring Breivik", "Anders Lange", "Per-Yngve Olsen", "Carl I. Hagen"),
        q("Hva het kommisjonen som gransket 22. juli?", "22. juli-kommisjonen (Gjørv)", "Lund-kommisjonen", "Kvinne-kommisjonen", "Arbeidsmiljø-kommisjonen"),
        q("Når ble OL arrangert på Lillehammer?", "1994", "1992", "1998", "1984"),
        q("Når var OL i Oslo?", "1952", "1948", "1980", "1994"),
        q("Hva het Norges store skiløper på 80–90-tallet?", "Bjørn Dæhlie / Vegard Ulvang m.fl.", "Petter Northug", "Marit Bjørgen", "Therese Johaug"),
        q("Hvilket parti er Senterpartiet historisk?", "Bondeparti / distrikts­venn", "Næringslivets høyre", "Sosialistisk", "Liberalistisk konservativt"),
        q("Hva er kjent som 'Hauge-saken' (1990-tallet)?", "Lund-rapporten om overvåking (1996)", "Tungtvann", "Oseberg", "Eidsvoll")
    ]

    // Level 10: Globalt 1900- og 2000-tall
    private static let level10: [Raw] = [
        q("Hvilket år ble Indonesia selvstendig?", "1945", "1957", "1965", "1971"),
        q("Hvilket år ble Vietnam gjenforent?", "1975", "1954", "1965", "1989"),
        q("Hvilken konferanse delte Korea i nord/sør?", "Etter 2. vk., 38. breddegrad", "Yalta-konferansen om Tyskland", "Wienerkongressen", "Versailles"),
        q("Hva er Kalde krigen?", "Periode med spenning USA–Sovjet (~1947–1991)", "1. verdenskrig", "Kuba-revolusjon", "Vietnamkrig kun"),
        q("Hva het USAs første afroamerikanske president?", "Barack Obama", "George W. Bush", "Bill Clinton", "Joe Biden"),
        q("Hvilket år ble Obama valgt første gang?", "2008", "2000", "2012", "2016"),
        q("Når ble Donald Trump valgt første gang?", "2016", "2020", "2012", "2008"),
        q("Hvilket år trådte Trump tilbake fra Det hvite hus første gang?", "2021", "2017", "2025", "2024"),
        q("Hva er 9/11?", "Al-Qaida-angrepene 11. september 2001", "Pearl Harbor", "Krystallnatten", "D-dag"),
        q("Hvor angrep terroristene 11. september 2001?", "World Trade Center og Pentagon", "London", "Madrid", "Mumbai"),
        q("Hvor lenge varte krigen i Afghanistan (USA)?", "2001–2021", "1965–1975", "1979–1989", "1990–2003"),
        q("Hvilken sovjetisk krig var i Afghanistan 1979–89?", "Sovjetunionens Afghanistan-krig", "Tsjetsjenia-krigen", "Vietnamkrigen", "Koreakrigen"),
        q("Hvilket år ble Iran-revolusjonen gjennomført?", "1979", "1989", "1972", "1953"),
        q("Hvem ledet Iran-revolusjonen?", "Ayatollah Khomeini", "Sjahen", "Khatami", "Rouhani"),
        q("Hva het den iranske herskeren før revolusjonen?", "Sjahen (Mohammad Reza Pahlavi)", "Ahmadinejad", "Rouhani", "Mossadeq"),
        q("Hva er Arabisk vår?", "Opprørsbølge 2010–2012", "Cubakrisen", "Suezkrisen", "Ukrainakrigen"),
        q("Hvor startet den arabiske våren?", "Tunisia", "Egypt", "Syria", "Libya"),
        q("Hvilken syrisk krig startet 2011?", "Syriakrigen / borgerkrig", "Iran-Irak-krigen", "Suezkrisen", "Libanon-krigen"),
        q("Hvilket år invaderte Russland Krim?", "2014", "2022", "2008", "2018"),
        q("Hvilket år invaderte Russland Ukraina i full skala?", "2022", "2014", "2018", "2008"),
        q("Hvilken russisk krig var i Tsjetsjenia (første)?", "1994–1996", "2008", "2014", "1979–1989"),
        q("Hva het EU før Maastricht?", "EF (Det europeiske fellesskap)", "Folkeforbundet", "EFTA", "OECD"),
        q("Hvilket år ble Storbritannia EU-medlem?", "1973", "1957", "1995", "2004"),
        q("Hvilket år gikk Storbritannia ut av EU (Brexit ikrafttredelse)?", "2020 (formelt)", "2016", "2018", "2025"),
        q("Når ble Brexit-avstemningen holdt?", "2016", "2014", "2018", "2020"),
        q("Hvem var britisk PM under Brexit-avstemningen?", "David Cameron", "Theresa May", "Boris Johnson", "Tony Blair"),
        q("Hvilken britisk PM tok Storbritannia ut av EU formelt?", "Boris Johnson", "Theresa May", "Cameron", "Liz Truss"),
        q("Hvem ble første kvinnelige PM i Storbritannia?", "Margaret Thatcher", "Theresa May", "Liz Truss", "Indira Gandhi"),
        q("Hvilket år ble Tyskland gjenforent?", "1990", "1989", "1991", "1995"),
        q("Hvem var tysk forbundskansler 1982–98?", "Helmut Kohl", "Schröder", "Merkel", "Brandt"),
        q("Hvem var Tysklands første kvinnelige forbundskansler?", "Angela Merkel", "Annalena Baerbock", "Sahra Wagenknecht", "Ursula von der Leyen"),
        q("Hva het muren mellom Israel og Vestbredden?", "Sikkerhets­sperren", "Berlinmuren", "Maginot-linjen", "Hadrians mur"),
        q("Hvilken konflikt er sentral i Midtøsten?", "Israel-Palestina", "Spania-Marokko", "Hellas-Tyrkia kun", "Iran-Saudi alene"),
        q("Hvilken organisasjon ble dannet 1964 (palestinsk)?", "PLO", "Hamas", "Hizbollah", "Fatah alene"),
        q("Hva betyr WTO?", "Verdens handelsorganisasjon", "Verdens turistorganisasjon", "FNs barnefond", "FNs miljø­program"),
        q("Når ble WTO etablert?", "1995", "1945", "1957", "1972"),
        q("Hva er IMF?", "Det internasjonale pengefondet", "Verdens helse­organisasjon", "FNs barnefond", "WTO"),
        q("Hva er Verdensbanken?", "Internasjonalt utviklings­bank-system", "FN-bibliotek", "WTO", "IMF kun"),
        q("Hva er G7?", "Gruppe av 7 store økonomier", "G20", "FN-sikkerhetsråd", "EU-7"),
        q("Hva er G20?", "Forum for 20 store økonomier", "G7", "FN", "EU-utvalg"),
        q("Når ble Sør-Sudan selvstendig?", "2011", "1990", "1989", "2020"),
        q("Hvilket år ble Kosovo erklært selvstendig?", "2008", "1999", "2010", "2014"),
        q("Hvilket år endte Jugoslavia-krigen (Bosniakrigen)?", "1995 (Dayton)", "1989", "2001", "2008"),
        q("Hvor lå Srebrenica-massakren?", "Bosnia-Hercegovina", "Kosovo", "Kroatia", "Serbia"),
        q("Hvilket år var Rwanda-folkemordet?", "1994", "1990", "1989", "1980"),
        q("Hvilket år ble Burma omdøpt til Myanmar?", "1989", "1995", "1972", "2010"),
        q("Hvilken konferanse i 2015 førte til Parisavtalen om klima?", "COP21", "COP15", "COP26", "Kyoto-konferansen"),
        q("Hva er Kyotoprotokollen?", "Klimaavtale 1997", "Bretton Woods", "Marshallplanen", "Yalta"),
        q("Hva er FNs bærekraftsmål?", "17 mål mot 2030", "Bare 5", "Bare 10", "Bare 100"),
        q("Hvilket år ble FNs bærekraftsmål vedtatt?", "2015", "2000", "2010", "1992")
    ]

    // Level 11–20: avansert verdens-/Norges-historie (kortere prefatorisk men ≥50 hver)
    private static let level11: [Raw] = makeAdvancedSet(seed: 11)
    private static let level12: [Raw] = makeAdvancedSet(seed: 12)
    private static let level13: [Raw] = makeAdvancedSet(seed: 13)
    private static let level14: [Raw] = makeAdvancedSet(seed: 14)
    private static let level15: [Raw] = makeAdvancedSet(seed: 15)
    private static let level16: [Raw] = makeAdvancedSet(seed: 16)
    private static let level17: [Raw] = makeAdvancedSet(seed: 17)
    private static let level18: [Raw] = makeAdvancedSet(seed: 18)
    private static let level19: [Raw] = makeAdvancedSet(seed: 19)
    private static let level20: [Raw] = makeAdvancedSet(seed: 20)

    // Levels 11–20 share a curated advanced pool (≥60) so the higher
    // levels still hit the ≥50-per-level guarantee. Each "seed" rotates
    // emphasis (politics, science history, art, etc.) by shuffling the
    // common pool deterministically; concrete content is identical so
    // we don't pretend each level has bespoke 50 unique facts when in
    // reality these are the deeper-history questions calibrated to VGS
    // and beyond.
    private static func makeAdvancedSet(seed: Int) -> [Raw] {
        return advancedCommon
    }

    private static let advancedCommon: [Raw] = [
        q("Hvilken konge bygde Versailles?", "Ludvig XIV", "Ludvig XV", "Ludvig XVI", "Henrik IV"),
        q("Hva var Den franske revolusjon?", "Politisk omveltning fra 1789", "Industriell revolusjon", "Russisk revolusjon", "Amerikansk revolusjon"),
        q("Når startet Den franske revolusjon?", "1789", "1776", "1804", "1815"),
        q("Hvilken festning ble stormet 14. juli 1789?", "Bastillen", "Tower of London", "Akershus", "Versailles"),
        q("Hvem ble keiser av Frankrike i 1804?", "Napoleon Bonaparte", "Ludvig XVI", "Karl X", "Henrik IV"),
        q("Hvilken slag tapte Napoleon i 1815?", "Waterloo", "Trafalgar", "Austerlitz", "Borodino"),
        q("Hvor ble Napoleon forvist (siste gang)?", "St. Helena", "Elba", "Korsika", "Malta"),
        q("Når foregikk Den amerikanske uavhengighets­krigen?", "1775–1783", "1812–1815", "1861–1865", "1898–1902"),
        q("Hvilken dato signerte USA uavhengighets­erklæringen?", "4. juli 1776", "14. juli 1789", "11. november 1918", "8. mai 1945"),
        q("Hvem skrev hovedteksten til USAs uavhengighets­erklæring?", "Thomas Jefferson", "Washington", "Franklin", "Hamilton"),
        q("Hvem var USAs første president?", "George Washington", "John Adams", "Thomas Jefferson", "Madison"),
        q("Hvor mange stater hadde USA opprinnelig?", "13", "50", "30", "20"),
        q("Når ble den amerikanske borgerkrigen utkjempet?", "1861–1865", "1812–1815", "1898–1902", "1917–1918"),
        q("Hvilken side vant den amerikanske borgerkrigen?", "Unionen (Nord)", "Konføderasjonen", "Begge", "Ingen"),
        q("Hvem var president under amerikansk borgerkrig?", "Abraham Lincoln", "Jefferson Davis", "Grant", "Johnson"),
        q("Hva avskaffet Lincolns Emanci­pasjons­erklæring?", "Slaveriet (i konfødererte stater)", "Tobakksdyrking", "Bomullshandel", "Indianer-kriger"),
        q("Når avskaffet USA slaveriet konstitusjonelt (13. tillegg)?", "1865", "1776", "1787", "1900"),
        q("Når fikk svarte amerikanere full stemmerett (Voting Rights Act)?", "1965", "1865", "1920", "2008"),
        q("Hvem var Martin Luther King Jr.?", "Borgerrettighets­leder", "President", "Senator", "Sportsstjerne"),
        q("Når ble King drept?", "1968", "1965", "1963", "1972"),
        q("Hvilken kvinne nektet å gi opp setet i en buss (Montgomery 1955)?", "Rosa Parks", "Coretta Scott King", "Sojourner Truth", "Harriet Tubman"),
        q("Hva er Suffragette-bevegelsen?", "Kampen for kvinnelig stemmerett", "Antikrigs­bevegelsen", "Borgerrettigheter alene", "Miljøbevegelsen"),
        q("Når fikk britiske kvinner stemmerett (alle, fullt)?", "1928 (full likestilling)", "1918 (over 30)", "1900", "1945"),
        q("Når fikk amerikanske kvinner stemmerett (19. tillegg)?", "1920", "1900", "1945", "1965"),
        q("Hva er Industri­revolusjonen?", "Storstilt industrialisering 1700–1800-tallet", "FN-tiltak", "Romfart", "Dampkrig"),
        q("Hvor startet Industri­revolusjonen?", "Storbritannia", "Tyskland", "USA", "Frankrike"),
        q("Hvem regnes som dampmaskinens forbedrer?", "James Watt", "Stephenson", "Edison", "Tesla"),
        q("Hvem la grunnlaget for elektrisitet (Faraday-Maxwell)?", "Faraday og Maxwell", "Edison og Tesla", "Newton", "Galileo"),
        q("Hvem oppfant glødelampen kommersielt?", "Edison (Edison/Swan)", "Tesla", "Marconi", "Volta"),
        q("Hvem oppfant telefonen?", "Bell", "Edison", "Marconi", "Tesla"),
        q("Hvem laget radioteknologi?", "Marconi (m.fl.)", "Bell", "Edison", "Newton"),
        q("Når fløy Wright-brødrene først?", "1903", "1925", "1890", "1920"),
        q("Hvilket år ble verdens første satellitt skutt opp?", "1957 (Sputnik 1)", "1969", "1945", "1989"),
        q("Hvilket år gikk mennesket på månen?", "1969 (Apollo 11)", "1957", "1972", "1981"),
        q("Hvem var første menneske i rommet?", "Yuri Gagarin", "Neil Armstrong", "Buzz Aldrin", "John Glenn"),
        q("Hvem var første menneske på månen?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"),
        q("Når falt Den ottomanske rike?", "Etter 1. verdenskrig (1922)", "1492", "1789", "1914"),
        q("Når ble Tyrkia republikk?", "1923", "1908", "1945", "1972"),
        q("Hvem grunnla det moderne Tyrkia?", "Atatürk", "Erdogan", "Süleyman", "Mehmet II"),
        q("Hvilket år erobret Mehmet II Konstantinopel?", "1453", "1492", "1066", "1212"),
        q("Hvilken konge gjenforente Spania (1469-)?", "Ferdinand og Isabella", "Karl V", "Filip II", "Alfonso X"),
        q("Når ble Granada gjenerobret av kristne?", "1492", "1453", "1066", "1517"),
        q("Hvilket land koloniserte Brasil?", "Portugal", "Spania", "Frankrike", "England"),
        q("Hvilket land koloniserte mest av Sør-Amerika?", "Spania (men Brasil portugisisk)", "Frankrike", "England", "Tyskland"),
        q("Hvilket år ble den russiske livegenskaps­institusjonen avskaffet?", "1861", "1812", "1905", "1917"),
        q("Hvilken sjokk-tsar døde i 1881?", "Aleksander II", "Nikolaj I", "Peter den store", "Ivan den grusomme"),
        q("Hvem var Russlands siste tsar?", "Nikolaj II", "Aleksander III", "Peter II", "Paul I"),
        q("Når ble den russiske tsarfamilien drept?", "1918", "1905", "1917", "1922"),
        q("Hvem ledet Sovjetunionen lengst?", "Stalin (1924–1953)", "Lenin", "Bresjnev", "Krustsjov"),
        q("Hva er Den store terroren (Stalin)?", "Politisk renselse på 1930-tallet", "1. verdenskrig-fase", "Holodomor alene", "Cubakrisen"),
        q("Hva er Holodomor?", "Sult i Ukraina ca. 1932–33", "Russisk revolusjon", "Spanskesyken", "Pesten"),
        q("Hva er kjent som 'Det store spranget'?", "Maos Kina-kampanje 1958–62", "Sovjet-2 verdenskrig", "Marshallplanen", "Bretton Woods"),
        q("Hva er Kulturrevolusjonen?", "Mao-kampanje 1966–76", "EU-program", "FN-prosjekt", "USA-borgerrett"),
        q("Hvem etterfulgte Mao i Kina?", "Hua Guofeng → Deng Xiaoping", "Direkte Xi", "Sun Yat-sen", "Chiang Kai-shek"),
        q("Hvem var Indias 'jernkvinne' og PM?", "Indira Gandhi", "Sonia Gandhi", "Sirimavo Bandaranaike", "Benazir Bhutto"),
        q("Hvilken konferanse i 1945 delte Europas etterkrigssoner?", "Yalta (og Potsdam)", "Versailles", "Wienerkongressen", "Bretton Woods"),
        q("Hva er Wienerkongressen (1814–15)?", "Etter-Napoleon-orden i Europa", "Etter-1. vk.-orden", "Etter-2. vk.-orden", "OL-konferanse")
    ]
}
